### ISSUE TITLE
Create database model and schema

### ISSUE THREAD

**Issue by SAR2652** [nyu-devops-inventory-fall22/inventory#6]
**As a** database developer 
 
**I need to:** 
1. to understand the requirements of storing data into the inventory
2. update the existing database schema and model
3. optimise the database design
 
**So that** we can retrieve the appropriate data to run our application
   
 ### Details and Assumptions
- [x] Add schema (attributes for the Inventory model)
- [x] Add a factory class in a file under tests folder for mock data.
- [x] Add a test for verifying instantiation of model object.
- [x] Connect database in the tests.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a working database
 When we start the database server using "flask run"
 Then we a have a ready to use database model
 ```

**Comment by aayushagrawal135** [comment]
A relational database with potential fields:

- item: str (example: chair, desk, fruits)
- expiry: datetime (for perishable products)
- category: str (can be helpful for group by queries, example: furniture)
- status: str (example: new, refurbished, return)
- created_at: datetime
- updated_at: datetime
