### ISSUE TITLE
Create the Inventory Record

### ISSUE THREAD

**Issue by aayushagrawal135** [nyu-devops-inventory-fall22/inventory#7]
**As a** Inventory Manager
 **I need** to add a record to the inventory
 **So that** I can store a new product in the database
   
 ### Details and Assumptions
- [x] Create function create_inventory_records which handles the case that when a record already exists in the database should return an error else insert the new record into the database
- [x] Add tests to ensure inventory record is being created correctly
- [x] Add tests to ensure if inventory record already exists cannot create a new record
- [x] Add tests to that if request from user comes in a format other than json return an error

 ### Acceptance Criteria     
```gherkin
 Given a create_inventory API in the flask application
 When a call is made to the above API with parameters such as name of record, quantity etc.
 Then a new inventory record is created in the database with the specified parameters.
 ```

**Comment by richa15997** [comment]
Updated table schema as below:
    ```
product_id = db.Column(db.Integer, primary_key=True, autoincrement=False)
    name = db.Column(db.String(63), nullable=False)
    condition = db.Column(db.Enum(Condition), nullable=False, default=Condition.NEW.name, primary_key=True)
    quantity = db.Column(db.Integer, nullable=False, default=0)
    reorder_quantity = db.Column(db.Integer, nullable=False, default=0)
    restock_level = db.Column(db.Integer, nullable=False, default=0)
    active = db.Column(db.Boolean, nullable=False, default=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
```
earlier Id column has been renamed to product_id and auto-increment set to False
earlier status columns has been renamed to condition. This column indicates whether the item is new, refurbished or returned
product_id and condition are a compound key in the table schema
Created the function create_products in the routes.py file which does the following:
Checks the content type of the input if it is a json file will proceed if not throws a 415_unsupported_content_type error
Checks if the given json contains a product_id and condition that already exist in the database. If already exists returns a 409_Conflict.
If product_id and condition do not exist in the database already, it stores the new product in the database
It calls the get function to return the location of the data stored in the database
Updated the find function in models.py which takes product_id and condition as arguments to query the Inventory database with these compound keys

Added below test cases to ensure all lines of code added by me have 100% code coverage

test_create_products
test_create_alreadyexists_product
test_create_product_invalid_content_type
