### ISSUE TITLE
Read Inventory Record

### ISSUE THREAD

**Issue by sakshambassi** [nyu-devops-inventory-fall22/inventory#8]
**As a** Inventory Manager
 **I need** to access an inventory record
 **So that** I can view its details such as the name and quantity.
   
 ### Details and Assumptions
 * Assumption: Flask server is already up and running
 * Assumption: Database Model has been defined
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have a read inventory record API in the server
 When I call it for a specific inventory record
 Then I get the id, name and quantity of the inventory record printed on the screen
 ```

**Comment by rishit13** [comment]
This PR contains the addition of `read inventory record `functionality. 

1. Functionality

Added `get_inventory_records:` to the routes.py file. This functionality takes `product ID` and `condition  ` as arguments from the user  and search the inventory database for the record and return the product id, name, quantity, condition, restock  level and reorder quantity. 

Here product d is passed in the URL and the condition is passed as part of the payload. These are used by the find function (present in the models.py file) to search for the particular record. 

2. Added the following test cases : 

- test_read_records
- test_read_non_existent_records 

Increased the routes.py code coverage from 95% to 100%.
